<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gibbs_mshots-image__container mshots-im_050c56</name>
   <tag></tag>
   <elementGuidId>c5c044a9-2626-4eb0-8842-fa5739594485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-87fa2bde-8f3a-4162-929f-a4bf4a1f79f0']/div/div/div/div[2]/div/button[2]/span/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mshots-image__container.mshots-image-visible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mshots-image__container mshots-image-visible</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s0.wp.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Fblank-canvas%2Ffredrickson%3Ffont_headings%3DCabin%26font_base%3DCabin%26site_title%3DFredrickson%26viewport_height%3D700%26language%3Den%26use_screenshot_overrides%3Dtrue?vpw=1600&amp;vph=1600&amp;w=600&amp;screen_height=3600&amp;count=0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>design-picker__option-name__fredrickson</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-87fa2bde-8f3a-4162-929f-a4bf4a1f79f0&quot;)/div[@class=&quot;wp-block&quot;]/div[@class=&quot;onboarding-block&quot;]/div[@class=&quot;gutenboarding-page designs&quot;]/div[@class=&quot;design-picker design-picker--theme-light&quot;]/div[@class=&quot;design-picker__grid&quot;]/button[@class=&quot;design-picker__design-option&quot;]/span[@class=&quot;design-picker__image-frame design-picker__image-frame-landscape design-picker__static&quot;]/div[@class=&quot;design-picker__image-frame-inside&quot;]/img[@class=&quot;mshots-image__container mshots-image-visible&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-87fa2bde-8f3a-4162-929f-a4bf4a1f79f0']/div/div/div/div[2]/div/button[2]/span/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s0.wp.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Fblank-canvas%2Ffredrickson%3Ffont_headings%3DCabin%26font_base%3DCabin%26site_title%3DFredrickson%26viewport_height%3D700%26language%3Den%26use_screenshot_overrides%3Dtrue?vpw=1600&amp;vph=1600&amp;w=600&amp;screen_height=3600&amp;count=0')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
